# Generated by Django 5.2 on 2025-09-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
    ]
