# Generated by Django 5.2 on 2025-09-27 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='instructor',
            name='access_token',
            field=models.TextField(default='12345', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(to='tutor.course'),
        ),
        migrations.AddField(
            model_name='response',
            name='conversation',
            field=models.ForeignKey(default='12345', on_delete=django.db.models.deletion.CASCADE, to='tutor.conversation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='tutor.course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default='12345', on_delete=django.db.models.deletion.CASCADE, to='tutor.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='assignment',
            field=models.ForeignKey(default='12345', on_delete=django.db.models.deletion.CASCADE, to='tutor.assignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='student',
            field=models.ForeignKey(default='12345', on_delete=django.db.models.deletion.CASCADE, to='tutor.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(default='12345'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='assignment',
            field=models.ForeignKey(default='12345', on_delete=django.db.models.deletion.CASCADE, to='tutor.assignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='12345'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='final_response',
            field=models.TextField(default='12345'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='prompt',
            field=models.TextField(default='12345'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='raw_response',
            field=models.TextField(default='12345'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='time',
            field=models.TextField(default='12345'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='access_token',
            field=models.TextField(default='12345', unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='student',
            name='instructor',
        ),
        migrations.AddField(
            model_name='student',
            name='instructor',
            field=models.ManyToManyField(to='tutor.instructor'),
        ),
    ]
