# Generated by Django 5.2 on 2025-09-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_remove_instructor_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.AutoField(default='12345', primary_key=True, serialize=False),
        ),
    ]
