# Generated by Django 5.2 on 2025-09-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_conversation_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
