# Generated by Django 5.2.6 on 2025-10-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_assignment_title_course_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='LLM_Response',
        ),
    ]
