# Generated by Django 5.2.6 on 2025-10-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_rename_response_llm_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': False},
        ),
    ]
