# Generated by Django 5.2.6 on 2025-11-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_alter_djangomigrations_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['assignment_id']},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['conversation_id']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_id']},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['instructor_id']},
        ),
        migrations.AlterModelOptions(
            name='llm_response',
            options={'ordering': ['response_id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id']},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
