# Generated by Django 5.2.6 on 2025-11-30 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_alter_assignment_options_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.assignment'),
        ),
    ]
