# Generated by Django 5.2.6 on 2025-11-30 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_llm_response_timestamp_question_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.conversation'),
        ),
    ]
