# Generated by Django 5.2.6 on 2025-12-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_alter_question_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
