# Generated by Django 5.2.6 on 2025-12-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_assignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
