# Generated by Django 5.2.6 on 2025-12-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_alter_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='llm_model',
            field=models.TextField(blank=True, null=True),
        ),
    ]
