# Generated by Django 5.2.6 on 2025-12-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_assignment_llm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
