####################################################################################################   
# __Database__.db Models
# Author: Dillon Sapp
#
# A database for storing students, LLM to student conversations, instructors, courses, their respective
# assignments and question 
####################################################################################################

from django.db import models

class Assignment(models.Model):
    """
    Represents an assignment specific to a course connected by an instructor for a student to work through with the LLM available.
    """
    #Model Fields
    assignment_id = models.AutoField(primary_key=True)
    title = models.TextField(blank=True, null=True)
    due_date = models.TextField(blank=True, null=True)
    settings = models.TextField(blank=True, null=True)
    llm_model = models.TextField(blank=True, null=True)
    course = models.ForeignKey('Course', models.CASCADE)
    file = models.FileField(upload_to='assignments/', blank=True, null=True)
    #Defines Model as String
    def __str__(self):
        return self.title
    #Model Metadata
    class Meta:
        ordering = ['assignment_id']
        db_table = 'Assignment'


class Conversation(models.Model):
    """
    Represents a conversation a student has had with the LLM regarding a specific assignment to include any prompt-response
    pairs generated by the LLM itself.
    """
    #Model Fields
    conversation_id = models.AutoField(primary_key=True)
    student = models.ForeignKey('Student', models.CASCADE)
    assignment = models.ForeignKey(
        Assignment,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    #Defines Model as String
    def __str__(self):
        return f"Conversation {self.conversation_id}"
    #Model Metadata
    class Meta:
        ordering = ['conversation_id']
        db_table = 'Conversation'


class Course(models.Model):
    """
    Represents a Canvas course connected by the instructor for the purpose of allowing a student to use the LLM with the course
    including a course-specific configuration.
    """
    #Model Fields
    course_id = models.AutoField(primary_key=True)
    name = models.TextField(blank=True, null=True)
    settings = models.TextField(blank=True, null=True)
    #Defines Model as String
    def __str__(self):
        return self.name
    #Model Metadata
    class Meta:
        ordering = ['course_id']
        db_table = 'Course'


class Instructor(models.Model):
    """
    Represents a unique instructor.
    """
    #Model Fields
    instructor_id = models.AutoField(primary_key=True)
    name = models.TextField(blank=True, null=True)
    email = models.IntegerField(blank=True, null=True)
    access_token = models.TextField(unique=True)
    courses = models.ManyToManyField(Course)
    #Define Model as String
    def __str__(self):
        return self.name
    #Model Metadata
    class Meta:
        ordering = ['instructor_id']
        db_table = 'Instructor'


class Question(models.Model):
    """
    Represents a a question from a specific assignment.
    """
    #Model Fields
    question_id = models.AutoField(primary_key=True)
    question_text = models.TextField()
    answer = models.TextField(blank=True, null=True)
    assignment = models.ForeignKey(Assignment, models.CASCADE, null=True, blank=True)
    conversation = models.ForeignKey(Conversation, models.CASCADE, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    #Defines Model as String
    def __str__(self):
        return self.question_text
    #Model Metadata
    class Meta:
        ordering = ['question_id']
        db_table = 'Question'


class LLM_Response(models.Model):
    """
    Represents a response from the LLM and its originating prompt. 
    This may include its own prompts, not just those originating from the student.
    """
    #Model Fields
    response_id = models.AutoField(primary_key=True)
    prompt = models.TextField()
    raw_response = models.TextField()
    final_response = models.TextField()
    time = models.TextField()
    conversation = models.ForeignKey(Conversation, models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    #Defines Model as String
    def __str__(self):
        return self.prompt
    #Model Metadata
    class Meta:
        ordering = ['response_id']
        db_table = 'Response'


class Student(models.Model):
    """
    Represents a unique student.
    """
    #Model Fields
    student_id = models.AutoField(primary_key=True)
    name = models.TextField(blank=True, null=True)
    email = models.TextField(blank=True, null=True)
    instructor = models.ManyToManyField(Instructor)
    courses = models.ManyToManyField(Course)
    access_token = models.TextField(unique=True)
    #Defines Model as String
    def __str__(self):
        return self.name
    #Model Metadata
    class Meta:
        ordering = ['student_id']
        db_table = 'Student'

class DjangoMigrations(models.Model):
    """
    A model for tracking Django Migrations (used by Django)
    """
    #Model Fields
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()
    #Defines Model as String
    def __str__(self):
        return self.name
    #Model Metadata
    class Meta:
        db_table = 'django_migrations'
